export const profile = {
	'id':8,
	'portalID':375,
	'firstName':'Ephraim',
	'lastName':'Gregor',
	'nickname':null,
	'address':null,
	'email':'ephraimgregor@gmail.com',
	'membershipType':'Full',
	'membershipNumber':'US2012030038',
	'membershipExpiration':'2017-09-05T00:00:00.000Z',
	'orgUnit':{
		'id':3,
		'name':'Children of the Lost Eden',
		'code':'NY-004',
		'type':'Domain'
	},
	'offices':[
		{
			'id':7,
			'name':'DC',
			'email':null,
			'type':'Primary',
			'parentOfficeID':null,
			'parentPath':'1.3.7',
			'parentOrgID':3,
			'userID':8,
			'roles':[
				'user_read_private',
				'user_update',
				'user_assign',
				'org_update',
				'office_update',
				'office_assign',
				'office_create_assistants'
			]
		}
	],
	'fullName':'Ephraim Gregor'
};
